DROP TABLE IF EXISTS BASE_CONTRACT;
CREATE TABLE BASE_CONTRACT (
  PRID varchar(5) NOT NULL,
  SYMBOL varchar(5) NOT NULL,
  STATUS varchar(3) NOT NULL,
  PRIMARY KEY (SYMBOL, PRID) USING BTREE
)AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;