CREATE TABLE IF NOT EXISTS 'BASE'.'CONTRACT' (
  'ID' int(10) unsigned NOT NULL AUTO_INCREMENT,
  'PRID' varchar(5) NOT NULL,
  'STATUS' varchar(3) NOT NULL,
  'SYMBOL' varchar(5) NOT NULL,
  PRIMARY KEY ('ID') USING BTREE
)AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;