CREATE TABLE IF NOT EXISTS 'BASE'.'CONTRACT_META' (
  'ID' int(10) unsigned NOT NULL AUTO_INCREMENT,
  'SYMBOL' varchar(5) NOT NULL,
  'DESC' varchar(8) NOT NULL,
  'HAND_VALUE' int(10) NOT NULL,
  'LEVERAGE' float(13,3) NOT NULL,
  'POINT_VAL' int(10) NOT NULL,
  'ATR' float(13,3) NOT NULL,
  PRIMARY KEY ('ID') USING BTREE,
  UNIQUE KEY 'UNI_SYMBOL' ('SYMBOL')
)AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;